name: PretparkCore
version: 1.0
main: nl.HorizonCraft.PretparkCore.Main
authors: [Cooltimmetje]
commands:
    fixgm:
        description: fixgm
    resetinv:
        description: resetinv het zelfde als rejoin
    resetinv:
        description: rejoin het zelfde als resetinv
    cc:
        description: cc
    maze:
        description: maze
    addride:
        description: addride
    setride:
        description: setride
    achievementride:
        description: achievementride
    unlockall:
        description: unlockall
    coins:
        description: coins
    exp:
        description: exp
    createvoucher:
        description: createvoucher
    redeem:
        description: redeem