name: PretparkCore
version: 1.0
main: nl.HorizonCraft.PretparkCore.Main
authors: [Cooltimmetje, 78wesley]
commands:
    fixgm:
        description: fixgm
    resetinv:
        description: resetinv het zelfde als rejoin
    rejoin:
        description: rejoin het zelfde als resetinv
    cc:
        description: cc
    maze:
        description: maze
    createwarp:
        description: createwarp
    warpstate:
        description: warpstate
    achievementride:
        description: achievementride
    unlockall:
        description: unlockall
    coins:
        description: coins
    exp:
        description: exp
    createvoucher:
        description: createvoucher
    redeem:
        description: redeem
    awardachievement:
        description: awardachievement
    revokeachievement:
        description: revokeachievement
    updateleaderboards:
        description: updateleaderboards
    powerup:
        description: powerup
    openbox:
        description: openbox
    specialdelivery:
        description: specialdelivery
    sd:
        description: sd
    myhorizon:
        description: myhorizon
    pieterpost:
        description: pieterpost
    setrank:
        description: setrank
    activatevip:
        description: activatevip
    warpmenu:
        description: warpmenu
    adminmenu:
        description: adminmenu
    swagmenu:
        description: swagmenu
    discord:
        description: discord
    box:
        description: box
    hcbuy:
        description: hcbuy