name: PretparkCore
version: 1.0
main: nl.HorizonCraft.PretparkCore.Main
authors: [Cooltimmetje]
commands:
    fixgm:
        description: fixgm
    resetinv:
        description: resetinv
    cc:
        description: cc
    maze:
        description: maze
    addride:
        description: addride
    setride:
        description: setride
    achievementride:
        description: achievementride